INSERT INTO Swimmer VALUES ('CA102', 'BAZIL MUZAFFAR', '18-JUN-1996', 'KARACHI CLUB');
SELECT * FROM Swimmer;
INSERT INTO Swimmer VALUES ('BC711', 'CHRIS CORNELL', '20-OCT-1980', 'SUNWAY CLUB');
SELECT * FROM Swimmer;
INSERT INTO Swimmer VALUES ('DT423', 'NAMEER RATHER', '10-DEC-1994', 'CHAMPIONS CLUB');
SELECT * FROM Swimmer;

INSERT INTO Event VALUES ('20', 'CHARITY SWIMMING');
SELECT * FROM Event;
INSERT INTO Event VALUES ('25', 'NATIONAL TROPHY');
INSERT INTO Event VALUES ('27', 'WORLD TROPHY');
SELECT * FROM event;

INSERT INTO Entry VALUES ('CA102', '20', '0.4500', NULL);
SELECT * FROM entry;
INSERT INTO Entry VALUES ('BC711', '25', '0.5000', NULL);
INSERT INTO Entry VALUES ('DT423', '27', '0.6250', NULL);
SELECT * FROM entry;