-- Generated by Oracle SQL Developer Data Modeler 4.1.2.895
--   at:        2016-01-25 18:28:21 SGT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g




DROP TABLE ACCOMODATION CASCADE CONSTRAINTS ;

DROP TABLE ATTRACTION CASCADE CONSTRAINTS ;

DROP TABLE BOOKING CASCADE CONSTRAINTS ;

DROP TABLE CUSTOMER CASCADE CONSTRAINTS ;

DROP TABLE DEPARTURE CASCADE CONSTRAINTS ;

DROP TABLE INTERCITY_TRAVEL CASCADE CONSTRAINTS ;

DROP TABLE PAYMENT CASCADE CONSTRAINTS ;

DROP TABLE STAFF CASCADE CONSTRAINTS ;

DROP TABLE TOUR CASCADE CONSTRAINTS ;

DROP TABLE TOURDAY CASCADE CONSTRAINTS ;

DROP TABLE TRANSPORT CASCADE CONSTRAINTS ;

CREATE TABLE ACCOMODATION
  (
    accom_id       NUMBER (8) NOT NULL ,
    accom_name     VARCHAR2 (50) NOT NULL ,
    accom_type     VARCHAR2 (50) NOT NULL ,
    accom_address  VARCHAR2 (200) NOT NULL ,
    accom_phone_no NUMBER (20) NOT NULL
  ) ;
ALTER TABLE ACCOMODATION ADD CONSTRAINT ACCOMODATION_PK PRIMARY KEY ( accom_id ) ;


CREATE TABLE ATTRACTION
  (
    attract_id   NUMBER (8) NOT NULL ,
    attract_name VARCHAR2 (200) NOT NULL ,
    start_time   DATE NOT NULL ,
    end_time     DATE NOT NULL ,
    day_number   NUMBER (2) NOT NULL ,
    departure_id NUMBER (8) NOT NULL ,
    transport_id NUMBER (8) NOT NULL
  ) ;
ALTER TABLE ATTRACTION ADD CONSTRAINT ATTRACTION_PK PRIMARY KEY ( attract_id, day_number, departure_id ) ;


CREATE TABLE BOOKING
  (
    booking_ref_number NUMBER (8) NOT NULL ,
    booking_date       DATE NOT NULL ,
    number_of_adults   NUMBER (2) NOT NULL ,
    number_of_children NUMBER (2) NOT NULL ,
    cust_id            NUMBER (8) NOT NULL ,
    departure_id       NUMBER (8) NOT NULL ,
    staff_id           NUMBER (8) NOT NULL ,
    special_book_note  VARCHAR2 (200) NOT NULL
  ) ;
ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_PK PRIMARY KEY ( booking_ref_number ) ;


CREATE TABLE CUSTOMER
  (
    cust_id      NUMBER (8) NOT NULL ,
    cust_fname   VARCHAR2 (50) NOT NULL ,
    cust_lname   VARCHAR2 (50) NOT NULL ,
    cust_address VARCHAR2 (200) NOT NULL ,
    cust_email   VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY ( cust_id ) ;


CREATE TABLE DEPARTURE
  (
    departure_id    NUMBER (8) NOT NULL ,
    departure_city  VARCHAR2 (20) NOT NULL ,
    start_date_time TIMESTAMP NOT NULL ,
    end_date_time   TIMESTAMP NOT NULL ,
    tour_code       NUMBER (3) NOT NULL
  ) ;
ALTER TABLE DEPARTURE ADD CONSTRAINT DEPARTURE_PK PRIMARY KEY ( departure_id ) ;


CREATE TABLE INTERCITY_TRAVEL
  (
    current_city      VARCHAR2 (30) NOT NULL ,
    next_city         VARCHAR2 (30) NOT NULL ,
    depart_date_time  TIMESTAMP NOT NULL ,
    arrival_date_time TIMESTAMP NOT NULL ,
    day_number        NUMBER (2) NOT NULL ,
    departure_id      NUMBER (8) NOT NULL ,
    transport_id      NUMBER (8) NOT NULL
  ) ;
ALTER TABLE INTERCITY_TRAVEL ADD CONSTRAINT INTERCITY_TRAVEL_PK PRIMARY KEY ( depart_date_time, current_city, next_city ) ;


CREATE TABLE PAYMENT
  (
    payment_id         NUMBER (8) NOT NULL ,
    payment_date       DATE NOT NULL ,
    amount_paid        NUMBER (7) NOT NULL ,
    payment_type       VARCHAR2 (50) NOT NULL ,
    booking_ref_number NUMBER (8) NOT NULL
  ) ;
ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_PK PRIMARY KEY ( payment_id ) ;


CREATE TABLE STAFF
  (
    staff_id    NUMBER (8) NOT NULL ,
    staff_fname VARCHAR2 (50) NOT NULL ,
    staff_lname VARCHAR2 (50) NOT NULL ,
    staff_email VARCHAR2 (100) NOT NULL
  ) ;
ALTER TABLE STAFF ADD CONSTRAINT STAFF_PK PRIMARY KEY ( staff_id ) ;


CREATE TABLE TOUR
  (
    tour_code           NUMBER (3) NOT NULL ,
    tour_number         NUMBER (4) NOT NULL ,
    tour_package        VARCHAR2 (100) NOT NULL ,
    adult_fare          NUMBER (5) NOT NULL ,
    child_fare          NUMBER (5) NOT NULL ,
    max_no_participants NUMBER (3) NOT NULL ,
    total_days          NUMBER (3) NOT NULL ,
    staff_id            NUMBER (8) NOT NULL
  ) ;
ALTER TABLE TOUR ADD CONSTRAINT TOUR_PK PRIMARY KEY ( tour_code ) ;


CREATE TABLE TOURDAY
  (
    day_number   NUMBER (2) NOT NULL ,
    departure_id NUMBER (8) NOT NULL ,
    accom_id     NUMBER (8)
  ) ;
ALTER TABLE TOURDAY ADD CONSTRAINT TOURDAY_PK PRIMARY KEY ( day_number, departure_id ) ;


CREATE TABLE TRANSPORT
  (
    transport_id                NUMBER (8) NOT NULL ,
    transport_type              VARCHAR2 (50) NOT NULL ,
    transport_provider          VARCHAR2 (50) ,
    transport_provider_phone_no NUMBER (20)
  ) ;
ALTER TABLE TRANSPORT ADD CONSTRAINT TRANSPORT_PK PRIMARY KEY ( transport_id ) ;


ALTER TABLE ATTRACTION ADD CONSTRAINT ATTRACTION_TOURDAY_FK FOREIGN KEY ( day_number, departure_id ) REFERENCES TOURDAY ( day_number, departure_id ) ON
DELETE CASCADE ;

ALTER TABLE ATTRACTION ADD CONSTRAINT ATTRACTION_TRANSPORT_FK FOREIGN KEY ( transport_id ) REFERENCES TRANSPORT ( transport_id ) ON
DELETE CASCADE ;

ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_CUSTOMER_FK FOREIGN KEY ( cust_id ) REFERENCES CUSTOMER ( cust_id ) ON
DELETE CASCADE ;

ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_DEPARTURE_FK FOREIGN KEY ( departure_id ) REFERENCES DEPARTURE ( departure_id ) ON
DELETE CASCADE ;

ALTER TABLE BOOKING ADD CONSTRAINT BOOKING_STAFF_FK FOREIGN KEY ( staff_id ) REFERENCES STAFF ( staff_id ) ON
DELETE CASCADE ;

ALTER TABLE DEPARTURE ADD CONSTRAINT DEPARTURE_TOUR_FK FOREIGN KEY ( tour_code ) REFERENCES TOUR ( tour_code ) ON
DELETE CASCADE ;

ALTER TABLE INTERCITY_TRAVEL ADD CONSTRAINT INTERCITY_TRAVEL_TOURDAY_FK FOREIGN KEY ( day_number, departure_id ) REFERENCES TOURDAY ( day_number, departure_id ) ON
DELETE CASCADE ;

ALTER TABLE INTERCITY_TRAVEL ADD CONSTRAINT INTERCITY_TRAVEL_TRANSPORT_FK FOREIGN KEY ( transport_id ) REFERENCES TRANSPORT ( transport_id ) ON
DELETE CASCADE ;

ALTER TABLE PAYMENT ADD CONSTRAINT PAYMENT_BOOKING_FK FOREIGN KEY ( booking_ref_number ) REFERENCES BOOKING ( booking_ref_number ) ON
DELETE CASCADE ;

ALTER TABLE TOURDAY ADD CONSTRAINT TOURDAY_ACCOMODATION_FK FOREIGN KEY ( accom_id ) REFERENCES ACCOMODATION ( accom_id ) ON
DELETE CASCADE ;

ALTER TABLE TOURDAY ADD CONSTRAINT TOURDAY_DEPARTURE_FK FOREIGN KEY ( departure_id ) REFERENCES DEPARTURE ( departure_id ) ON
DELETE CASCADE ;

ALTER TABLE TOUR ADD CONSTRAINT TOUR_STAFF_FK FOREIGN KEY ( staff_id ) REFERENCES STAFF ( staff_id ) ON
DELETE CASCADE ;


-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            11
-- CREATE INDEX                             0
-- ALTER TABLE                             23
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
